### PR TITLE
For PHP 7

### PR DESCRIPTION
**Pull request by remicollet**
With PHP 7.0:

```
$ phpunit AllTests.php 
PHPUnit 5.6.5 by Sebastian Bergmann and contributors.

...............E............................................      60 / 60 (100%)

Time: 93 ms, Memory: 6.00MB

There was 1 error:

1) Net_DNS2_ParserTest::testParser with data set #14 ('NSAP', 'example.com. 300 IN NSAP 0x47...151.00')
Net_DNS2_Exception: failed to generate resource record

/work/GIT/netdns2/Net/DNS2/RR.php:187
/work/GIT/netdns2/Net/DNS2/RR.php:465
/work/GIT/netdns2/Net/DNS2/Packet/Response.php:152
/work/GIT/netdns2/Net/DNS2/Packet/Response.php:94
/work/GIT/netdns2/tests/Net_DNS2_ParserTest.php:221
/work/GIT/netdns2/tests/AllTests.php:88
/work/GIT/netdns2/tests/AllTests.php:111

ERRORS!
Tests: 60, Assertions: 132, Errors: 1.
```

### CODE REVIEW

**Comment by remicollet** [comment]
See https://3v4l.org/QoeGU  (var_dump("0x47"==0x47) in different PHP versions)

With this fix:

```
$ php56 /usr/bin/phpunit  AllTests.php  -v
PHPUnit 5.6.5 by Sebastian Bergmann and contributors.

............................................................      60 / 60 (100%)

Time: 82 ms, Memory: 5.00MB

OK (60 tests, 133 assertions)

$ php70 /usr/bin/phpunit  AllTests.php  -v
PHPUnit 5.6.5 by Sebastian Bergmann and contributors.

............................................................      60 / 60 (100%)

Time: 82 ms, Memory: 4.00MB

OK (60 tests, 133 assertions)

```

**Comment by mikepultz** [comment]
Thanks Remi,

It was just three changes in NSAP.php file though, so I don't really need all the other changes.

Mike

**Comment by remicollet** [comment]
But the commit about include_path is needed, else we are enable to run the test suite downstream (in Fedora build system), else PHPunit don't find some of its files.

And the commit to switch to dataProvider is still useful IMHO, as it give better output in case of error (with data set #14 ('NSAP'...) to understand which case is failing.

**Comment by mikepultz** [comment]
I understand, but it breaks my build and test system, which I assume means it may break other systems as well. There are a lot of existing downstream build systems that import this package- including Fedora, so I assume it worked before this change?

 

I’m considering breaking off a v2.x branch so that I can implement some other backwards incompatible changes- I can include these changes in that as well.

 

Mike

**Pull request closed without merging**
